name: kryptr

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kryptr
      POSTGRES_PASSWORD: kryptr_dev
      POSTGRES_DB: kryptr
    ports:
      - '5432:5432'
    volumes:
      - kryptr_pg:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kryptr']
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - kryptr_redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  kryptr_pg:
  kryptr_redis:
